cfpb/hmda-test-files

python/lar_constraints.py
Refactors v613_const and v635_const to separate logic.
This should enable better debugging of consistent validation fails.
=> Const logic

python/edit_file_test_tool.ipynb, python/rules_engine.py, python/test_file_generator.py
=> closes #34, #35, #36, #37

python/test_file_generator.py
Closes #278 
Closes #277 
Closes #276 
Closes #275 
Closes #274
=> Adds files for 675 series

python/test_file_generator.py
Closes #279 
Closes #280 
Closes #281 
Closes #282 
Closes #283
=> creates 676 test files

python/test_file_generator.py
Closes #286 
Closes #287 
Closes #288 
Closes #289 
Closes #290
=> creates 678 test files

python/test_file_generator.py
Closes #295 
Closes #296 
Closes #297
=> creates v679 files

python/generate_error_files.py, python/rules_engine.py, python/test_file_generator.py
Adds Q600 to the rules engine
Creates Q600 edit test file
Creates quality folder for quality test files
=> add code for q600 file generation. Closes #375

python/rules_engine.py
- Adds q602 rules
- Fixes a bug in q601 where NA dates were not properly accounted for
=> closes #377 

python/test_file_generator.py
=> change logic for v609 edit file creation

python/lar_generator.py, python/rules_engine.py
=> add logic for s2155 for v624

python/rules_engine.py, python/test_file_generator.py, schemas/lar_schema.json
=> add s2155 changes for v662

python/rules_engine.py
=> add s2155 changes for v665

python/rules_engine.py
=> add s2155 changes for v668

python/rules_engine.py, schemas/lar_schema.json
=> add s2155 changes for v669

python/rules_engine.py, python/test_file_generator.py
=> add s2155 logic for v670

python/rules_engine.py, python/test_file_generator.py, schemas/lar_schema.json
=> add s2155 changes for v672

python/rules_engine.py, python/test_file_generator.py, schemas/lar_schema.json
=> add s2155 changes for v676

python/rules_engine.py, schemas/lar_schema.json
=> add s2155 changes for v678

python/rules_engine.py, schemas/lar_schema.json
=> add s2155 changes for v679

python/rules_engine.py
=> add s2155 changes for v680

python/rules_engine.py, schemas/lar_schema.json
=> add s2155 changes for v682

python/rules_engine.py, schemas/lar_schema.json
=> add s2155 changes for v683

python/rules_engine.py, schemas/lar_schema.json
=> add s2155 changes for v686

python/rules_engine.py, schemas/lar_schema.json
=> add s2155 changes for v688

python/rules_engine.py, schemas/lar_schema.json
=> add s2155 changes for v689

python/rules_engine.py, schemas/lar_schema.json
=> add s2155 logic for v690

python/rules_engine.py, python/test_file_generator.py, schemas/lar_schema.json
=> add s2155 logic for v693, requires an additional edit file to be created

python/rules_engine.py, schemas/lar_schema.json
=> add logic for s2155 changes to v694

python/rules_engine.py
=> add s2155 logic for v704

python/rules_engine.py
=> add s2155 logic for v705

python/rules_engine.py, schemas/lar_schema.json
=> add s2155 logic for v706

python/rules_engine.py, schemas/lar_schema.json
=> add s2155 changes for v707

python/rules_engine.py
=> add s2155 changes for q615

python/rules_engine.py
=> add s2155 changes for q616

python/lar_constraints.py, python/rules_engine.py, schemas/lar_schema.json
Also integrates TS data in config.yaml
=> Update S2155 exemption codes to 1111 from -1

python/lar_constraints.py, python/rules_engine.py
Close #568, #569, #570, #571, #572, #573, #574, #575, #576, #577, #578, #579
=> add 709-715 edits

python/macro_edits_procedure.py
Adds a class object for constructing files that fail Macro Quality edits while passing Syntax and Validity edits.
=> adding class for macro edits

python/large_test_files.py
=> adding s304 implementation

python/utils.py
Close #596 
This adds a function to the utils.py set for changing the institution of existing test file data.
=> adding change bankfunction for adjusting institution specifications

python/edit_fails_by_row.py, python/lar_generator.py, python/large_test_files.py, python/rules_engine.py, python/utils.py
=> move check_digit_gen and char_string_gen to utils

python/rules_engine.py
=> change v617 to cast as a float

python/rules_engine.py
=> add logic fix to v617.

python/rules_engine.py
=> Q616_1 adding conversion of blanks to float

python/generate_clean_files.py
Close #612 
Implements a log file for generate clean files.py.
=> adding log file properties

python/generate_clean_files.py, python/generate_error_files.py, python/test_file_generator.py
Close #567  
This places clean files in a directory according to institution name.
=> adding institution name to the directory path for clean files.

python/large_test_files_script.py
=> moving row by row function

python/configurations/geographic_data.yaml, python/generate_clean_files.py, python/lar_generator.py, python/rules_engine.py, python/test_file_generator.py
=> adding geographic configurations

python/rules_engine.py
=> fixing q600 edit

python/rules_engine.py
=> adjusting rules for string inputs.

python/rules_engine.py
=> adding changes to q608

python/rules_engine.py
=> Q607 fix implementation

python/rules_engine.py
=> adding edit fix to Q612.

python/rules_engine.py
=> adding v602 and s302 fixes for generating a clean file

python/rules_engine.py
=> adjusting age range for Q614 edit.

python/configurations/test_filepaths.yaml, python/file_generator.py
=> adding file_generator class and test filepaths.

python/rules_engine.py
=> adjusted so that action date can be the same as application date.

python/rules_engine.py
=> reverting change from the last PR

readme.md
=> Documentation update

python/configurations/geographic_data.yaml, python/file_generator.py, python/lar_generator.py, python/rules_engine.py, python/test_file_generator.py
=> adding new crosswalk data and generalizing variable names

2019/python/lar_constraints.py, 2019/python/rules_engine.py
=> v644-2 2019 edit changes

2019/python/lar_constraints.py, 2019/python/rules_engine.py, 2019/python/test_file_generator.py
Close #694 
from [Platform Issue 2774](https://github.com/cfpb/hmda-platform/issues/2774)
=> v648-2 edits

2019/python/rules_engine.py, 2019/python/test_file_generator.py
=> 2019 q644 changes

2019/python/rules_engine.py, 2019/python/test_file_generator.py
=> 2019 q643 changes

2019/python/rules_engine.py, 2019/python/test_file_generator.py
=> 2019 changes to Q633

2019/python/rules_engine.py, 2019/python/test_file_generator.py
=> 2019 q632 changes

2019/python/lar_constraints.py, 2019/python/rules_engine.py, 2019/python/test_file_generator.py
=> 2019 v677 changes. 

2019/python/lar_constraints.py, 2019/python/rules_engine.py, 2019/python/test_file_generator.py
=> adding q645 and fixing small error.

2018/python/configurations/edit_report_config.yaml, 2018/python/configurations/test_filepaths.yaml, 2018/python/file_generator.py, 2018/python/generate_edit_report.py, 2019/python/configurations/edit_report_config.yaml, 2019/python/configurations/test_filepaths.yaml, 2019/python/file_generator.py, 2019/python/generate_edit_report.py, 2019/python/rules_engine.py
=> Adding edit reports for 2018 and 2019 (and fixing Q645 error)

2018/python/file_generator.py, 2018/python/generate_2018_error_files.py, 2018/python/rules_engine.py, 2019/python/file_generator.py, 2019/python/generate_2019_error_files.py, 2019/python/rules_engine.py
=> Provide functionality for validating quality files. 

2019/python/rules_engine.py, 2019/python/test_file_generator.py
=> adding q647 edit and test conditions

2019/schemas/lar_schema.json
=> 2019 changes to LAR schema

2019/python/lar_constraints.py, 2019/python/lar_generator.py, 2019/python/rules_engine.py, 2019/python/test_file_generator.py
=> changing file years

2019/python/rules_engine.py
=> taking exemption code out of v696_3

2019/python/lar_constraints.py
Close #716 
Tested. Edit Report was generated. No syntax or validity edits present in the resulting clean file.
=> fixing lar_constraints not to add extra rows

2018/python/file_generator.py, 2019/python/file_generator.py
Close #659 
Functions have been tested.
=> adding custom row generator

2018/python/test_file_generator.py, 2019/python/test_file_generator.py
=> fixing q613 edit

2018/python/test_file_generator.py, 2019/python/test_file_generator.py
=> fixing q608 to pass syntax validity

2018/python/lar_constraints.py, 2018/python/rules_engine.py, 2019/python/lar_constraints.py, 2019/python/rules_engine.py
=> removing v645_1

2018/python/lar_constraints.py, 2018/python/rules_engine.py, 2019/python/lar_constraints.py, 2019/python/rules_engine.py
=> removing v633_2

2018/python/lar_constraints.py, 2018/python/rules_engine.py, 2019/python/lar_constraints.py, 2019/python/rules_engine.py
Close #739
This edit was modified to remove condition one of v649_1. Previous condition two becomes
condition one.
=> Removing v649_1

2018/python/lar_constraints.py, 2018/python/rules_engine.py, 2019/python/lar_constraints.py, 2019/python/rules_engine.py
=> removing v643_2

2018/python/lar_constraints.py, 2018/python/rules_engine.py, 2019/python/lar_constraints.py, 2019/python/rules_engine.py
=> removing edit v640_2

2020/python/configurations/newman_bank_config.yaml
A configuration file to use with newman bank for testing
Related to [#3677](https://github.com/cfpb/hmda-platform/issues/3677)
=> added config file for newman bank
